### ISSUE TITLE
Crew Transfer Submarine bug

### ISSUE THREAD

**Issue by Finalsong** [Yonaguni/EuropaStation#101]
https://gyazo.com/ec5bc1d892b6c1a5ee5a1f4d0699032c

**Comment by Zuhayr** [comment]
Jesus I really broke that shuttle.

**Comment by mwerezak** [comment]
It seems like it's generating an announcement every time the submarine moves. 
1st announcement is the shuttle being called.
2nd announcement is leaving "centcom" and moving to the intransit area.
3rd is leaving the intransit area and moving to the station.
4th is the actual arrived message.
