### ISSUE TITLE
Recent Major Bugs.

### ISSUE THREAD

**Issue by Finalsong** [Yonaguni/EuropaStation#104]
-~~Telecomms dies easily because it can't get any power. (No solars)~~
-External airlocks have a solar control console, now useless.
-~~There's a bunch of oldcode tiles in the dorms.~~
-~~The CC z-level is now simulated. It's dark and can explode.~~
-Panic siphons don't work.
-Neither do airlocks.

//Minor Bugs.\\\
Anime hairstyles and colorful hair are still in the game.

**Comment by Zuhayr** [comment]
Why would we remove colourful hair? Hair dye is a thing.

**Comment by Finalsong** [comment]
@Zuhayr It's mostly a joke, really. If there's any reason to it, I'd say that the poor, poor, colonists can't afford it/commerce won't reach them.

**Comment by WrongEnd** [comment]
No longer using box. Will create new issue for panic syphons.
