### ISSUE TITLE
IPCs get hallucinations from radiation buildup.

### ISSUE THREAD

**Issue by Loneguyfly** [Yonaguni/EuropaStation#105]
Simple here. Set up SM as an IPC while unprotected, or just go run next to it. You'll start hallucinating.

**Comment by Zuhayr** [comment]
Radiation does not cause hallucinations, this is the SM itself doing it.

**Comment by Spacemanspark** [comment]
Paradise has a fix for this, I believe.
Maybe.

**Comment by Zuhayr** [comment]
Going to close this as it's not a bug and Bay isn't going to change it anytime soon. If we change it it will be a feature.
