### ISSUE TITLE
Setting yourself to anything higher than "Never" on Citizen greys out all options.

### ISSUE THREAD

**Issue by Loneguyfly** [Yonaguni/EuropaStation#106]

**Comment by PsiOmegaDelta** [comment]
I assume "Citizen" is the same as assistant in classic SS13?
If so, this is how it's always been since time immemorial.

**Comment by Loneguyfly** [comment]
It greys itself out, too.

**Comment by PsiOmegaDelta** [comment]
Ah. It's probably some great hardcoded filtering on the title "Assistant" then.
