### ISSUE TITLE
When teleported to a new turf, issues arrise

### ISSUE THREAD

**Issue by NobleCaos** [Yonaguni/EuropaStation#108]
Essentially you get one tile (your own) with light, other than that it's darkness as if there were no lights

**Comment by Zuhayr** [comment]
More info?

**Comment by NobleCaos** [comment]
When using the admin teleport (within the player panel), at least when teleported to the ERT gear up place and mercship, as those were the only ones I attempted to teleport to. Complete darkness other than the one tile you were currently standing in.

**Comment by PJB3005** [comment]
Lack of `forceMove()` maybe?

**Comment by Zuhayr** [comment]
#124
