### ISSUE TITLE
Areas with non-dynamic lighting have buggy lighting.

### ISSUE THREAD

**Issue by DrChef** [Yonaguni/EuropaStation#124]
When I go inside the cargo submarine, there are no visible
![space station 13 2015-08-16 024155](https://cloud.githubusercontent.com/assets/8340147/9292811/df0c8368-43c1-11e5-8e4f-bb6752d7dde4.png)
 light.

**Comment by Zuhayr** [comment]
#108
#111

**Comment by PJB3005** [comment]
For some reason the shuttle's luminosity is 0

**Comment by Zuhayr** [comment]
Probably better to direct input to the issue on the Bay tracker, since the bug isn't Europa's code.
