### ISSUE TITLE
Transfer sub cockpit is depressurized

### ISSUE THREAD

**Issue by NobleCaos** [Yonaguni/EuropaStation#127]
When launched (manually) the cockpit is depressurized

**Comment by ZeroTheDragon** [comment]
Cockpit also depressurized when launched in any form.

**Comment by Zuhayr** [comment]
I think this is due to the right-hand side shuttle window. The left-hand side has a full atmosphere of air on its turf, but the right loses it all after launch.

**Comment by Zuhayr** [comment]
No longer an issue since the map now doesn't include one.
