### ISSUE TITLE
Clicking on a wall causes it's sprite to vanish.

### ISSUE THREAD

**Issue by ZeroTheDragon** [Yonaguni/EuropaStation#129]
Clicking any normal steel wall causes the sprite to vanish. The server still registers it as there but the players can no longer see it.

**Comment by 5crownik007** [comment]
I can corroborate this. yep. disappearing walls. I am magic.

**Comment by Zuhayr** [comment]
Yeah I'm not sure what's causing this. I had to force an initialization call to make them display at all, so it's possible there's some root issue in update_icon() or update_material() that can be solved to fix it completely.

**Comment by TheDZD** [comment]
I tried looking into this issue a bit, and have learned a few things that might be of help.
- After clicking a wall, its `overlays` var when viewed from VV goes from `/list (5)` to `/list (0)`.
 - This issue does not happen on Bay dev.
- The wall's air var is null prior to clicking on a wall, after being clicked it becomes a reference to a gas_mixture datum.
 - This does happen on Bay dev.
- Damaging the wall (such as by firing a laser cannon blast at it) fixes the invisibility issue, and prevents the wall from becoming invisible unless it is repaired.

**Comment by Zuhayr** [comment]
It sounds like it's calling overlays.Cut() somewhere that it really shouldn't be.

**Comment by TheDZD** [comment]
It seems that [this](https://github.com/Yonaguni/EuropaStation/blob/master/code/modules/linda/linda_turf.dm#L200) is the line causing the issue. Removing it fixed walls disappearing upon being clicked, and allowed me to comment out the contents of [this](https://github.com/Yonaguni/EuropaStation/blob/master/code/modules/europa/hooks/ocean.dm#L1) proc and walls remained visible both at roundstart and upon being clicked.
