### ISSUE TITLE
Seafloor water is not static

### ISSUE THREAD

**Issue by ZeroTheDragon** [Yonaguni/EuropaStation#133]
The entire oceans water can be drastically changed by pumping hotter or colder gas through heat exchange pipes exposed to the ocean. What kind of silly-ness is this? I changed the seawater from 20C to -24C  by hooking a cooler up to the engine cold gas loop.

**Comment by Nienhaus** [comment]
That is amazing.

**Comment by GinjaNinja32** [comment]
seawater starts at -24C

**Comment by ZeroTheDragon** [comment]
Bug does not exist apparently and has come from incorrect measurements.
