### ISSUE TITLE
Server frame rate too jittery

### ISSUE THREAD

**Issue by ZeroTheDragon** [Yonaguni/EuropaStation#134]
Servers framerate is too jittery. Compare it to something like /vg/ at http://ss13.pomf.se/ and see the difference. This can be fixed by going into the servers config file and lowering the variable TICKRATE and raising the variable TICKCOMP. It also has a side affect of making Zero shut up about how jittery the server is.

**Comment by GinjaNinja32** [comment]
this is not a bug, this is a config issue.

this is also subjective, and (at least AFAIK) Europa is running on the same ticklag as Bay is (i.e. 0.9).

**Comment by ZeroTheDragon** [comment]
This isn't a bug indeed. I was told to leave it here so everyone could see it.

**Comment by SkowronX** [comment]
Changing the tickrate creates inconsistency with movement transitions. A lower tickrate with current movement speeds appears sluggish with the higher framerate.

**Comment by Zuhayr** [comment]
Tracket is for bugs. If someone can port/implement the movement smoothing code that was referenced on the BYOND forums the ticklag can be lowered but otherwise this is something for discussion on IRC.
