### ISSUE TITLE
H/E pipes do not exchange heat with ocean turfs

### ISSUE THREAD

**Issue by ZeroTheDragon** [Yonaguni/EuropaStation#135]
Maximum temperature needed for the engine to run and power the station is. -24c The engine will not power the station if the seawater is 20c

**Comment by ZeroTheDragon** [comment]
Actually it turns out the heat exchange pipes do not exchange with seawater. I have been informed the seawater temp starts at -24c

**Comment by Zuhayr** [comment]
Geothermal engine is not going to be based on a HE pipeline. Are you referring to the TEG?

**Comment by ZeroTheDragon** [comment]
I'm referencing the H/E pipes now. They don't exchange heat with the seawater? I think?

**Comment by Zuhayr** [comment]
Oceans are simulated now, should be fine.
