### ISSUE TITLE
Seafloor is above all other objects and mobs.

### ISSUE THREAD

**Issue by ninjacha** [Yonaguni/EuropaStation#143]
The seafloor is above all obj and mobs, but not displayed over them, meaning if you want to pull, you can't just ctrl+click or if you want to turn something on, you can't because the seafloor is there.

**Comment by Zuhayr** [comment]
This is a mouse_opacity issue on the seafloor overlay image, I am not very bright.

**Comment by Zuhayr** [comment]
BYOND doesn't want images to respect mouse opacity so I can't work around this currently. Using objects allows mouse opacity to be set but massively bloats the roundstart time.

**Comment by ninjacha** [comment]
rip
