### ISSUE TITLE
Passport prevents spawning of IDs if player lacks wallet.

### ISSUE THREAD

**Issue by Techhead0** [Yonaguni/EuropaStation#149]
If you spawn with a passport, it goes in your ID slot.
ID spawning then will attempt to put ID in wallet, and failing the existence of wallets, `H.equip_to_slot_or_del(C, slot_wear_id)`.
As ID slot is occupied, this deletes the ID.

**Comment by Zuhayr** [comment]
equip_to_slot_or_del() isn't used anywhere in passport spawning, where are you seeing this? I haven't seen this issue on-server or during testing either.

**Comment by Techhead0** [comment]
During ID spawning, not passport spawning.
https://github.com/Yonaguni/EuropaStation/blob/master/code/game/jobs/job_controller.dm#L556-L561

**Comment by Zuhayr** [comment]
This no longer appears to be the case, are you sure you didn't join as a civilian role with no default ID?
