### ISSUE TITLE
Hardsuit cosmetic issue.

### ISSUE THREAD

**Issue by Finalsong** [Yonaguni/EuropaStation#197]
https://gyazo.com/4a0dc56455799872e8bba0a24d979792

Basically, some hairstyles stick outside of the diving suits. Also, diving suit's description still says "Low pressure environments"

**Comment by NobleCaos** [comment]
This issue is also with several other head items.

**Comment by Loganbacca** [comment]
The "low pressure environment" suit descriptions will be the non-europa diving suits.
