### ISSUE TITLE
Shuttle lighting is broken again.

### ISSUE THREAD

**Issue by Zuhayr** [Yonaguni/EuropaStation#232]
Same issue as earlier in the year, everything is black except a 3x3 radius around the mob. Going to assume this is a Bay issue since we haven't touched lighting at all.

**Comment by NobleCaos** [comment]
It's been broken for a long time @Zuhayr it was never fixed...

**Comment by PsiOmegaDelta** [comment]
The lighting issue in general was fixed by https://github.com/Baystation12/Baystation12/pull/11499
