### ISSUE TITLE
You can light lighters, matches and such underwater

### ISSUE THREAD

**Issue by NobleCaos** [Yonaguni/EuropaStation#234]

**Comment by Loganbacca** [comment]
Feature?
http://www.exotac.com/Stormproof-Matches

**Comment by NobleCaos** [comment]
I was told by @Zuhayr to make it

**Comment by Loganbacca** [comment]
Yea, that was mostly a comedy response.

**Comment by Zuhayr** [comment]
I will probably just make this go off the waterproof var so stormproof matches can be a thing.
