### ISSUE TITLE
Vents have wrong obj path

### ISSUE THREAD

**Issue by Dennok** [Yonaguni/EuropaStation#254]
![ventmistake](https://cloud.githubusercontent.com/assets/7734424/11596012/435863fa-9abb-11e5-929b-7419e72bd15f.png)

**Comment by Dennok** [comment]
all vent on map is wrong

**Comment by WrongEnd** [comment]
Can you explain further? They're wrong doesn't give me much to work with.

**Comment by Dennok** [comment]
its a PIPES no vents

**Comment by WrongEnd** [comment]
I figured that was the problem. I'll fix it when I get home.

**Comment by Dennok** [comment]
:+1:
