### ISSUE TITLE
Language Bugs.

### ISSUE THREAD

**Issue by Finalsong** [Yonaguni/EuropaStation#266]
Humans and other species can speak any language in the game, even if they're a non-Admin. Furthermore, broken wooden floors seem to be illuminated 24/7, regardless of light level.

**Comment by Zuhayr** [comment]
Not a bug, the alien whitelist is disabled for Europa. I might have to remove all the alien languages though since most of the speaking species don't exist in our lore.

**Comment by Finalsong** [comment]
Ah. Close it, then?

**Comment by Zuhayr** [comment]
Eh. Leave it for now.

**Comment by Zuhayr** [comment]
Removed 'em all. Still have 'Chimpanzee' as an option which could be a problem.

**Comment by Zuhayr** [comment]
#372
