### ISSUE TITLE
cO2 waste fliter incorrectly set up

### ISSUE THREAD

**Issue by WrongEnd** [Yonaguni/EuropaStation#276]
Has no connections to other pipes currently.

https://i.gyazo.com/edd17bf0a8c9283fab89e1b9e1e96c68.png

**Comment by Loganbacca** [comment]
I don't think that's a waste filter. The pump to the south of it is pushing gas towards the filter.
Also, there is no oxygen storage.

**Comment by Zuhayr** [comment]
All atmos machines were removed so this is no longer relevant.
