### ISSUE TITLE
Mechs/Pods do not protect the pilot from drowning

### ISSUE THREAD

**Issue by Vivalas** [Yonaguni/EuropaStation#28]

**Comment by Zuhayr** [comment]
Interesting. I would have thought that a pressurized suit would be calling return_air() on itself, not the turf. Did you test this while you were running off the internal tank?

**Comment by Vivalas** [comment]
Yep. Although I turned the tank on after the pod was flooded with water in both cases I tested this, I don't know if turning it on before being submerged would help or if the code is even that advanced.

**Comment by Zuhayr** [comment]
It shouldn't matter.
