### ISSUE TITLE
ID-locked vending machines and terminals cannot be accessed due to a lack of ID.

### ISSUE THREAD

**Issue by WrongEnd** [Yonaguni/EuropaStation#282]
See title.

**Comment by Loganbacca** [comment]
Do we want anything like these having access restrictions, or should that be based around access to the rooms they are found in?

**Comment by Zuhayr** [comment]
My intent is to remove the concept of card access entirely. Passwords or something would be much better.

**Comment by Zuhayr** [comment]
Vending machines have been removed, no longer a concern.
