### ISSUE TITLE
Add in a player limit.

### ISSUE THREAD

**Issue by WrongEnd** [Yonaguni/EuropaStation#29]
Only allow 40 active characters on the station, and allow overflow to observe only.

**Comment by Vivalas** [comment]
Observers still take up bandwidth, don't know if a hard player limit on joining would be necessary.

**Comment by Zuhayr** [comment]
The concern is the map design rather than connection count, we can cheerfully handle 100 observers if we have anything approaching a reasonable server.

**Comment by Finalsong** [comment]
I feel 40 is a bit low, but I don't know. I'm just worried I won't be able to play whenever given the chance. *shrug

**Comment by Zuhayr** [comment]
Going to close this for now as the concept of the game has changed so significantly and it needs rediscussion.
