### ISSUE TITLE
Debug showing up

### ISSUE THREAD

**Issue by Nienhaus** [Yonaguni/EuropaStation#303]
Log: [debug] event controller process hung at tick #3342. Process was unresponsive for 90.09 seconds and was restarted. Last task: 0. Last Object Type: null
Diary: [debug:diary] event controller process hung at tick #3342. Process was unresponsive for 90.09 seconds and was restarted. Last task: 0. Last Object Type: null
Log: [debug] event controller process was killed at tick #3342.
Diary: [debug:diary] event controller process was killed at tick #3342.

This was before getting my rank back too.

**Comment by Techhead0** [comment]
Event controller hung on the Camera Damage event.
Likely due to improper use of the `--` operator here: https://github.com/Yonaguni/EuropaStation/blob/master/code/modules/events/camera_damage.dm#L33
