### ISSUE TITLE
Blind from sleeping/reconnecting.

### ISSUE THREAD

**Issue by Techhead0** [Yonaguni/EuropaStation#305]
As in issue https://github.com/Baystation12/Baystation12/issues/11771.

**Comment by Zuhayr** [comment]
So we need to port Baystation12:11781

**Comment by PsiOmegaDelta** [comment]
The quickfix is as simple as https://github.com/PsiOmegaDelta/Baystation12/commit/66112636c85a0be30d2bec5da7f22534553d2f10.
