### ISSUE TITLE
Water is completely broken.

### ISSUE THREAD

**Issue by Zuhayr** [Yonaguni/EuropaStation#314]
It is largely invisible and floods through every available non-dense turf irrespective of doors or walls in the way instantly after a tile is exposed. This one is my fault and is due to the water flow controller not being properly implemented; noting it here so it's clear and reported and I don't forget to try and fix it.

**Comment by PJB3005** [comment]
I just experienced the opposite of this. I broke a window into the ocean and no water came through.
