### ISSUE TITLE
Newguns megathread.

### ISSUE THREAD

**Issue by Zuhayr** [Yonaguni/EuropaStation#341]
Will add/remove from this as I fix 'em.

- [X] Variable laser cannot fire taser shots
- [x] Lasers use gunshot sound
- [x] Can't tell if the breech is open from examine.
- [x] Load fail due to open breech has no feedback
- [x] Fire fail due to open breech has no feedback
- [x] Precision laser cannot fire.
- [x] Breech loading rifles eject their shells when firing, is this desirable?
- [x] Loading magazines does not chamber a round automatically.
- [x] Removing magazines removes chambered rounds.
- [x] Revolver has pink grip.
- [x] burst laser shotgun can't fire
- [x] laser cannon can't fire
- [x] dropped guns remain (wielded)
- [x] autocannon does not accept a magazine
- [x] shotgun pump has no feedback
- [x] .45 SMG can be reloaded from an ammo box.
- [x] 9mm magazine does not exist.
- [x] 5.7mm magazine/ammo do not exist.
- [x] 45 mag does not exist.
- [x] Capgun ammo does not exist.
- [x] variable caliber lasers begin with the incorrect caliber set.
- [ ] Speedloaders use empty icon_state always.
- [ ] Magazine icons do not update based on current ammo.

**Comment by comma** [comment]
Double-barelled shotgun implementation fails with weirdness.
Chamber is child of /breech/ with max_shots set to 2 and to HOLD_CASINGS, and with firemodes.

```

/obj/item/gun_component/chamber/ballistic/breech/shotgun
	icon_state="shotgun_double"
	weapon_type = GUN_SHOTGUN
	max_shots = 2
	handle_casings = HOLD_CASINGS
	load_method = SINGLE_CASING
	
	firemodes = list(
		list(mode_name="fire one barrel at a time", burst=1, fire_delay=0, burst_accuracy=null, dispersion=null),
		list(mode_name="fire both barrels at once", burst=2, fire_delay=null, move_delay=5, burst_accuracy=null, dispersion=null),
		)
```

1.Open breech
2.Load two shells
3.Close breech.
4.Shoot. One bullet will fly out on any firemode.

Third shell appears, staying in chambered. You can unload two shells, one or two of which will be spend depending on firemode. Examining shows there's a shell left inside, but you can't get it, it claims gun is empty. VV shows it's not spent (at least desc), but you still can't fire it. It's in chambered var.

**Comment by Zuhayr** [comment]
Leave this up in case more bugs appear.

**Comment by comma** [comment]
Speedloaders use empty icon_state always

**Comment by comma** [comment]
Cannot VV guns with names starting with . like ".357 revolver"

**Comment by Zuhayr** [comment]
Cannot reproduce, with and without \improper.

http://i.imgur.com/HOkoM4g.png

**Comment by Zuhayr** [comment]
I'm dumb, forgot the other issues.

**Comment by Zuhayr** [comment]
#419
