### ISSUE TITLE
Wounds never clot

### ISSUE THREAD

**Issue by comma** [Yonaguni/EuropaStation#347]
1.Get a .45 revolver
2.Shoot yourself in the leg.
3.Bleed out to death

It made a 18.2  damage wound
bleed_timer was stuck at -0.800001

With gauze not doing anything to wounds of that size, this means that without a surgeon, every single cut above gauze threshold is lethal.

**Comment by comma** [comment]
I'd suggest letting bandages stop or at least slow bleedout considerably.
Ability to sutrue yourself might be nice too.

**Comment by Zuhayr** [comment]
Self-surgery would be nice but I'm not really sure how that could be done effectively. Check if you're standing on a chair?

**Comment by Zuhayr** [comment]
Needs a 'Realism' tag.

**Comment by comma** [comment]
I'd still like bandages to have some meaning even for bigger wounds, as a first-aid thing, so there's a gradation between 'totally untreated' and 'surgical procedure'. Something that either slows dying considerably, or puts you in a limbo where you're neither recovering nor deteriorating.

**Comment by Loganbacca** [comment]
To be fair, shooting yourself in the leg with a .45 would do an enormous amount of damage.

**Comment by comma** [comment]
Yeah, issue is more about not being able to do /anything/ about it but watching yourself bleeding out.

**Comment by Vivalas** [comment]
To be completely honest, shooting yourself in the leg with a .45 caliber bullet is not something you would be able to stem the bleeding of, by yourself at least. If I understand this correctly applying gauze doesn't stop the bleeding, but slows down the bleeding until it is almost a trickle.

**Comment by comma** [comment]
I am sure that shooting yourself with guns in real life is bad for health, question is how close to that it should work in the game. 
With one shot one kill system, anyone without legitimate access to the doctor is screwed after receiving a single gunshot wound, which would happen much often seeing how guns are supposed to be much more widespread now. While it's nice that guns are actual menace, imo it would only encourage shooting first in any conflict situation involving guns if you are not sure you'd be able to get treated afterwards.

**Comment by Vivalas** [comment]
I agree some sort of field surgery should be made for this, but you shouldn't be able to to treat this by yourself with just a roll of gauze. Perhaps the applying pressure thing is a good idea, such as if you are buckled into a chair + gauze can stem the bleeding completely, but you are stuck in that chair until someone comes and helps apply a proper tourniquet.

**Comment by Loganbacca** [comment]
Have a walking condition in there. So after bandaging and are walking you wont bleed much, but if you run you have a high chance of ruining the bandage, then you start bleeding out again.

That way taking a bullet doesn't kill you super fast, but does mean you have to start heading for proper treatment, albeit carefully.

Field treatment could take it a step further and stop the bleeding by suturing (or stapling - yay ghetto surgical equipment) the wound, although you would still need to be careful to avoid ripping them out. 

Maybe include a higher chance of the wound getting infected if treated outdoors so field treatment isn't a one stop fix.

Also, start most roles with a basic (and I mean _basic_) med kit, i.e. pain killers and gauze.

**Comment by Zuhayr** [comment]
Master has the ability to put pressure on your wounds, no longer relevant.
