### ISSUE TITLE
Compile errors?

### ISSUE THREAD

**Issue by Vivalas** [Yonaguni/EuropaStation#362]
I'm assuming this is due to my BYOND version being out of date but upon downloading a fresh version of the code I get numerous "cannot have proc definition inside other proc" type errors.

**Comment by Vivalas** [comment]
Yeah I'm going to close this, my BYOND version is hilariously out of date.

**Comment by PsiOmegaDelta** [comment]
Can confirm that this indeed looks like pre-509 compilation errors.
