### ISSUE TITLE
Swimming in Borderworld is Deadly 2 : Drowning Boogaloo

### ISSUE THREAD

**Issue by comma** [Yonaguni/EuropaStation#381]
A long awaited sequel to #349
While after fixing #349 you do not explode in fine mist, you now drown certainly to deth.
Currently you are unable to get out of river if you fall in, as Move Upwards does nothing near the edge.

**Comment by Techhead0** [comment]
Well, at least this one is closer to realism.

**Comment by Zuhayr** [comment]
There's a //TODO in multiz water code so I am exempt from blame.

**Comment by Loganbacca** [comment]
Isn't this basically how water/ledges work in dwarf fortress? If so then it's probably fine as is. Right? Riiiight?

Being serious though, shallows should probably be visible from the underwater zlevel, with maybe a slope leading up to the shallows if that's possible?

**Comment by Zuhayr** [comment]
How would you handle making shallows visible from the level below?

**Comment by Zuhayr** [comment]
Move Upwards and Move Downwards are now functional.
