### ISSUE TITLE
Paint does nuffin

### ISSUE THREAD

**Issue by comma** [Yonaguni/EuropaStation#382]
1.Spawn bucket of paint
2.Splash on the ground
3.Splash on the things
4.Notice how nothing changes, .color var remaining unset

**Comment by Zuhayr** [comment]
What kind of ground did you splash it on?

**Comment by comma** [comment]
Concrete

**Comment by Zuhayr** [comment]
My fault, paint is currently removed.

**Comment by Zuhayr** [comment]
Fixed on master.
