### ISSUE TITLE
Tgui templ files not found

### ISSUE THREAD

**Issue by mattroks101** [Yonaguni/EuropaStation#398]
![](http://puu.sh/nhI9N/26e1bc86a0.png)

I dunno how many are missing, but I know that the drink dispenser is currently broken.

Broken UI's: 
 - [x] Drink dispenser
 - [x] Jukebox

**Comment by mattroks101** [comment]
![](http://puu.sh/nhXgV/d672ee2a44.png) Jukebox isn't there either.

**Comment by Nienhaus** [comment]
RIP my smooth beats.

**Comment by Loganbacca** [comment]
I've edited the original issue comment to include a list of the broken UI's. I'll check them off as I fix them.

**Comment by Loganbacca** [comment]
Drink dispenser fixed in #404

**Comment by Loganbacca** [comment]
Jukebox fixed in #406

**Comment by Loganbacca** [comment]
Marking this done for now. If any more come up feel free to make another issue.
