### ISSUE TITLE
Disappearing and inaccessible items.

### ISSUE THREAD

**Issue by 5crownik007** [Yonaguni/EuropaStation#423]
Screwdrivers and wirecutters that spawn in toolboxes and toolbelts are inaccessible and transparent.
and 10mm pistols from scrappers/salvagers/whatever are invisible when held and when placed in containers, cannot be taken out, and are also transparent.
Wirecutters and screwdrivers spawned outside of containers do not have this issue, and the 10mm pistol spawns in a holster.

**Comment by Zuhayr** [comment]
It's an issue with layering on 510 that we haven't managed to isolate yet.

**Comment by Zuhayr** [comment]
Fixed on master
