### ISSUE TITLE
water_act() incorrectly firing on machinery

### ISSUE THREAD

**Issue by Loganbacca** [Yonaguni/EuropaStation#471]
`the terminal (#1) (/obj/machinery/console): Destroy()
qdel(the terminal (#1) (/obj/machinery/console))
the terminal (#1) (/obj/machinery/console): ex act(3)
the terminal (#1) (/obj/machinery/console): water act(0)
the terminal (#1) (/obj/machinery/console): process()
machinery (/datum/controller/process/machinery): internal process machinery()
machinery (/datum/controller/process/machinery): doWork()
machinery (/datum/controller/process/machinery): process()`

`/obj/machinery/console` in a `/turf/simulated/floor/tiled turf`
Turf was not flooded, and had no fluid objects in it.

**Comment by Zuhayr** [comment]
Pretty sure this is fixed now.
