### ISSUE TITLE
Aeolus map issues.

### ISSUE THREAD

**Issue by Zuhayr** [Yonaguni/EuropaStation#476]
- [ ] Empty rooms and maint, need fluff
- [x] Black pipes against black plating are hard to see.
- [x] Flooring icons need to be less high-contrast
- [x] Space tiles under IA office windows
- [x] Armory starts with only tasers
- [x] Flooring under sec locker room windows, should be plating
- [x] Carpetting in arcade room entrance looks off, double layered due to lighting
- [ ] Pumps in atmos, too many, overly complicated and redundant.
- [ ] Scrubber pipes don't actually go into the waste loop, through the filters and into the tanks
- [ ] Air tank start closed off from supply distro
- [x] Triple TEGs in the engine cause too much temperature equalization, cold loop don't have enough pressure differential for the circulators to work properly
- [x] Pressure tank (fuel) in incinerator missing icon
- [x] Floating safe in bar backroom
- [x] Bar backroom missing shotgun
- [x] Guest pass terminal and blast door button in bridge need to be pixel shifted
- [ ] No blast doors in slime lab
- [x] Useless cloning pod in slime lab, because xenoarch X xenobio never happened
- [ ] Messaging server upload/control rooms are freezing cold, SMES not wired properly, floating APC.  Also need better labeling
- [x] Intercom sticking out in the RD's office
- [ ] Toxins launch room shoot bombs into... space?
- [x] Cargo missing computers
- [x] Random steel/wood in CMO's bedroom
- [x] Unconnected pipes in security maintenance
- [x] Escape shuttle dock need airlocks
- [ ] Too many closets in engineering workshop, use racks for tools maybe?
- [ ] Primary tool storage need less tables and random tools, more other things
- [x] Misplaced sink in kitchen cold room
- [x] There are no blast doors on the east and west sides of the SM core.
- [x] Decals need updating to the new floor tile pattern.
- [x] Medbay tiling is too high contrast.
- [x] Plating icons are still noisy.
- [x] All the canisters in Atmos start off empty.
- [ ] Fire doors in maintenance with no corresponding air alarm.
- [ ] Not many APCs/subareas in maint.
- [ ] EVA is in the middle of nowhere (surrounded by maint).
- [ ] Medical storage is largely empty.
- [ ] Several out of alignment decals (warning line corners)
- [x] Teleporter is out of canon/lore.
- [ ] Holodeck isn't mapped.
- [ ] Security briefing room is FUCKING ENORMOUS (and empty). Seats at the  back can't see the person up the front.
- [ ] Security in general is enormous and oddly shaped - blobby gear room made of glass and grilles is weird.
- [x] Detective office shouldn't exist, Detectives don't. Likewise IA office.
- [ ] Fleet Officer and Operations Officer need offices/bedrooms.
- [ ] Crew dormitories/mess hall needs to exist.
- [ ] Cultural Attache office/dorms need to exist.
- [ ] Away mission prep area/shuttles should exist? Talk to Discord.
- [x] Runtime and Ian need to be changed.
- [x] Kitchen doesn't have all the Bay machines.
- [x] Jobs need roundstart spawn points added.
- [ ] What even is the latejoin pod?
- [ ] R&D is huge for no reason. Similarly, Robotics.
- [x] Science maint goes nowhere.
- [x] Consoles still use the NanoTrasen logo.

**Comment by Zuhayr** [comment]
Aeolus is in the WIP folder now so I'm going to close this.

**Comment by Flip-Sandwich** [comment]
~blast from the past~

**Comment by Zuhayr** [comment]
get on discord nerd

**Comment by Flip-Sandwich** [comment]
where

**Comment by Zuhayr** [comment]
https://discord.gg/0q6V27i2zxW6aAiI
