### ISSUE TITLE
AI following appears to crash client.

### ISSUE THREAD

**Issue by Zuhayr** [Yonaguni/EuropaStation#478]
#### Description of issue

When playing as AI and attempting to track somebody using the Follow With Camera verbs or by clicking on their name in the text pane, the client says 'Now following [X] on camera.' as normal, and then often (but not always) crashes. There appears to be no correlation between crashes and the specific person being followed - sometimes following person X will crash, sometimes it won't.

Does _not_ crash if the trackee can't be located ('System error. Cannot locate [x].', or 'Target is not near any active cameras.')

#### Steps to reproduce 

Play as AI, attempt to track somebody.

#### Length of time in which bug has been known to occur

No idea.

#### Server revision & Game ID

Revision unknown
Game ID: bLw-alBE
BYOND version 510

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by PsiOmegaDelta** [comment]
What if the AI attempts to track someone already fairly centered in view?
I recall the client has an increasing tendency to go bork the further the view jumps as it just cannot seem to handle loading a large number of icons/states well.

**Comment by Zuhayr** [comment]
Not sure, this was @thasc 's issue

**Comment by Zuhayr** [comment]
Doing ANYTHING AT ALL seems to cause client crashes as AI, it is extremely unstable.

**Comment by Zuhayr** [comment]
Fixed in a previous PR. Problem was a missing `..()` in AI life().
