### ISSUE TITLE
you can put your evoked powers in the bin. also in lockers.

### ISSUE THREAD

**Issue by Zuhayr** [Yonaguni/EuropaStation#481]
#### Description of issue

you can put your evoked powers in the bin. also in lockers. because that's a thing you can do. put your bare hands into the bin.

and put them on others and FIX IT FIX TI FIXT I

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Flip-Sandwich** [comment]
i put my bare hands in the bin, eject them, pick up my bare hands, put them on a person, and store my bare hands safely in the locker

**Comment by Loganbacca** [comment]
Sounds like a feature to me
