### ISSUE TITLE
SPACE magazine on the computers

### ISSUE THREAD

**Issue by EmperorJon** [Yonaguni/EuropaStation#534]
#### Description of issue

It should probably be removed relatively quickly given it goes into lots of detail about BayLore and Nyx and such.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Zuhayr** [comment]
Uggghhhh I thought I removed this shit.
