### ISSUE TITLE
Rods placed in space lack a sprite

### ISSUE THREAD

**Issue by Cairo283** [Yonaguni/EuropaStation#549]
#### Description of issue
Rods, when used on space tiles to attempt to make lattice, lack an actual sprite for the lattice.
Other than that, it still seems to work just fine as a lattice, allowing you to move around it and such.

#### Difference between expected and actual behavior

That shit should have a sprite, yo.

#### Steps to reproduce 

Place some rods on a tile of space. You will need to right-click on the tile to actually "see" them.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Zuhayr** [comment]
![image](https://cloud.githubusercontent.com/assets/2468979/23349960/008ed19e-fd07-11e6-88af-786380feeea6.png)
