### ISSUE TITLE
Test issue pls ignore.

### ISSUE THREAD

**Issue by Yonaguni** [Yonaguni/EuropaStation#55]
Trying to get webhooks working on Agatha.

**Comment by PJB3005** [comment]
10/10 would issue again

**Comment by PJB3005** [comment]
AAAAND i just realised there's an unsubscribe button.

**Comment by Yonaguni** [comment]
Yep.

**Comment by PJB3005** [comment]
Oh, and it doesn't work. because I'm following the repo.

**Comment by Yonaguni** [comment]
Sorry. I'll leave off if you want. Just trying to get the listener bot to work.
