### ISSUE TITLE
Lighting causes serious lag when qdel() fails en masse.

### ISSUE THREAD

**Issue by Zuhayr** [Yonaguni/EuropaStation#553]
#### Description of issue
Lighting overlays (/obj/effect/light) fail to qdel() and cause massive lag when they suddenly hard delete all at once.

#### Difference between expected and actual behavior
Lighting overlays should qdel cleanly.

#### Steps to reproduce 
Join a round and cause a massive lighting update via power cut/admin secrets panel.

#### Length of time in which bug has been known to occur
Ever since the new lighting system was added.

#### Server revision & Game ID
Server revision: master - 2016-12-15
46199492c467c887da6a84abfba88b910e1aa388 
Game ID: bL4-dFQY

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Loganbacca** [comment]
I've added some null checks to the light Destroy() proc, which will hopefully prevent any weird issues. In practice though I couldn't actually get it to break when I was testing it.

**Comment by PJB3005** [comment]
Uh, wouldn't pooling be a good idea here?

**Comment by Zuhayr** [comment]
@PJB3005 pooling relies on the objecting being able to qdel doesn't it?

**Comment by Zuhayr** [comment]
http://i.imgur.com/FulfQ2j.png Didn't change it at all.

**Comment by Loganbacca** [comment]
@Zuhayr have you got any steps to recreate it exactly, I haven't been able to reproduce it locally.

**Comment by EmperorJon** [comment]
I seem to always have it locally. I'll take a look at when it starts popping up/if I have to have joined the round and actually done anything.

**Comment by EmperorJon** [comment]
Joined the round and it just happened immediately. Didn't change any lighting, use a torch, anything. 30 to 40 reports more or less immediately.

**Comment by PJB3005** [comment]
@Zuhayr not necessarily though if a dangling reference is left with pooling it could cause objects taken from the pool to misbehave.

**Comment by EmperorJon** [comment]
@Loganbacca I haven't tried Aeolus or anything but one thing that just struck me is I'm working on my own silly map currently and I'm not getting any qdel failures at all... Given you can't replicate it, is this something that's _only_ occurring on the Katydid or something?

**Comment by Loganbacca** [comment]
Honestly I don't know. I was testing it with Katydid.

**Comment by EmperorJon** [comment]
That really is odd. I'll start up all the other maps I can and see if it's unique to the Katydid for me.

**Comment by Zuhayr** [comment]
I haven't seen this happening for awhile now - it may have been fixed by a BYOND update or by @Lohikar's GC changes. Closing for now.
