### ISSUE TITLE
Lighting overlay/shadow overlap

### ISSUE THREAD

**Issue by EmperorJon** [Yonaguni/EuropaStation#562]
#### Description of issue

Not sure exactly what I'm seeing here

![image](https://cloud.githubusercontent.com/assets/4721936/21287353/4306c768-c461-11e6-9338-644c60f13979.png)

It looks like the shadows created by the lights on the left are making the lighting on the right darker where it... shouldn't actually be darker? Probably just a limitation of the system right now.

#### Difference between expected and actual behavior

I don't think 
![image](https://cloud.githubusercontent.com/assets/4721936/21287360/63a45fee-c461-11e6-9ac5-8a9529013ce0.png)
that shadow should exist?

#### Steps to reproduce 

Just look at the above shuttle.

#### Server revision & Game ID

Server revision: master - 2016-12-17
abf00af4c358cafa9c8a5a5009a8ec91de26cafe 
Game ID: bL6-b7gw

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Zuhayr** [comment]
It's actually just a zone where neither of the left lights are lighting. Look at the gradient from the top right light to the indicated area.

**Comment by Techhead0** [comment]
What Zuhayr said. This is actually intended behavior, if it does look a little funny due to the placement of the lights.

**Comment by EmperorJon** [comment]
I think I'm just confused with how it looks like it's darker on the right than on the left, even though the lights are within the same tile relatively speaking... Probably optical illusion.

**Comment by Techhead0** [comment]
In the turf, the left triangle is lit by 4 lights, the right by 2, and the top and bottom triangles each by 3.

**Comment by Loganbacca** [comment]
At some point I should probably go over the whole map and reposition all the lights so you dont get weird effects like this.
