### ISSUE TITLE
Boxes sometimes have their contents layering under the UI

### ISSUE THREAD

**Issue by Minijar** [Yonaguni/EuropaStation#570]
#### Description of issue

![](https://puu.sh/xfNG6/9557de822f.jpg)
The items are also unclickable

#### Difference between expected and actual behavior
To be clickable and not vanishing into darkness.

#### Steps to reproduce 
This happened with a box of pepper spray grenades but it was fine with he flashbang box so go figure.

#### Server revision & Game ID

Server revision: master - 2017-08-20
668ae5cdd610f501562325ecbe78079a13c2ad8b
Game ID: bP5-cyuA

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Zuhayr** [comment]
Fixed on Yonaguni PR.
