### ISSUE TITLE
Issues with Uplink guns

### ISSUE THREAD

**Issue by N8-Toe** [Yonaguni/EuropaStation#572]
#### Description of issue
SMGs from the uplink do not come with ammo and their type of ammo, 10mm, can not be bought

the concealed pistol does not come with a silencer and is not easily concealable, not fitting in pockets or jackets. It's ammo, 9mm, can not be bought as well. 

#### Difference between expected and actual behavior
described above

#### Steps to reproduce 
use traitor uplink to spawn SMG and pistol 

#### Server revision & Game ID

Server revision: master - 2017-08-20
668ae5cdd610f501562325ecbe78079a13c2ad8b
Game ID: bP5-cyuA

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Zuhayr** [comment]
Should be fixed by #565.
