### ISSUE TITLE
Autopsy not recognizing open wounds

### ISSUE THREAD

**Issue by N8-Toe** [Yonaguni/EuropaStation#574]
#### Description of issue
when giving an autopsy to mobs with massive brute damage the scanner does not recognize if the wound is open, stating it needs to be opened with a scalpel when this can not be done. clicking with a scalpel asks which organ you want to separate.

#### Difference between expected and actual behavior
expected autopsy scanner to scan wound, did not do so

#### Steps to reproduce 
acquire dead body, store bought or home made works. try to do autopsy on severely damaged sections.  

#### Server revision & Game ID

Server revision: master - 2017-08-20
668ae5cdd610f501562325ecbe78079a13c2ad8b
Game ID: bP5-cyuA

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Zuhayr** [comment]
Should be fixed by #565.
