### ISSUE TITLE
octopodes have no mask slot/airlocks cycle out air, without adding water

### ISSUE THREAD

**Issue by zamolxius** [Yonaguni/EuropaStation#613]
#### Description of issue
tried to go in water, suffocated from lack of air in the airlock, could not use a mask due to lack of mask slot.

#### Difference between expected and actual behavior

should be able to use/have a mask slot  /airlock should cycle out water for air

#### Steps to reproduce 
try using a mask as an octopode

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Zuhayr** [comment]
You can use a helmet for internals currently, airlocks cycling in water is going to need to wait on a proper water handling system (which is in the works, just not finished yet). Going to close this as none of it is a bug and it's an unfocused feature request.
