### ISSUE TITLE
Effects cannot be interacted with

### ISSUE THREAD

**Issue by M0ppi** [Yonaguni/EuropaStation#617]
#### Description of issue
Any effect, for example, blood, vomit, runes etc. cannot be interacted with. Found this out noticing cult runes can't be invoked. Hovering your mouse or right-clicking the tile won't show them like they're supposed to.

#### Server revision & Game ID
master - 2017-09-21

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Zuhayr** [comment]
Should be fixed in #616
