### ISSUE TITLE
Robomans loose resistance to cold/pressure on being rejenivated

### ISSUE THREAD

**Issue by Ratvar** [Yonaguni/EuropaStation#619]
#### Description of issue
Be android prothesic man
Be atmosimmune/coldimmune
Be rejenivated
You now freeze and die to pressure
#### Difference between expected and actual behavior
Be pressure/coldresistant
Not be pressure/coldresistant

#### Steps to reproduce 
Be roboman
Rejenivate
Water yourself

**Comment by Zuhayr** [comment]
Not a bug, they don't have cold and pressure resistance to the degree that they can survive unshielded in the open ocean.
