### ISSUE TITLE
Neo-Corvid Smocks do not fit fully.

### ISSUE THREAD

**Issue by CommanderXor** [Yonaguni/EuropaStation#629]
#### Description of issue
When wearing the Neo-Corvid smocks, it leaves the legs and groin of your Neo-Corvid uncovered.

#### Difference between expected and actual behavior
The smock should cover the groin and legs of the person wearing it.

#### Steps to reproduce 
Step 1) Go to loadout.
Step 2) Go to uniforms and casual dress.
Step 3) Pick what ever Neo-Corvid smock you need.
Step 4) Go to general.
Step 5) Look at your Neo-Corvid.

#### Length of time in which bug has been known to occur
Not sure, since I started.

#### Server revision & Game ID
master - 2017-09-22
bQB-bg5y

#### Issue bingo

- [X] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by Zuhayr** [comment]
````
[4:48 PM] Zuhayr: oh I might have fucked that up
[4:48 PM] Zuhayr: when I redid the tails
[4:48 PM] Zuhayr: previously they were higher
[4:48 PM] Zuhayr: return of the dixel
````
