### ISSUE TITLE
Circuit Imprinters are greedy bastards

### ISSUE THREAD

**Issue by CoolfoolFTW** [Yonaguni/EuropaStation#642]
#### Description of issue
Circuit Imprinters eat some of the resources you put inside of it. For gold it eats 4 ingots

#### Difference between expected and actual behavior
It shouldn't treat ingots and sheets like they are being recycled.

#### Steps to reproduce 
1. Put in ingots or sheets into the imprinter.
2. Rage as it devours your rare metals. 

#### Length of time in which bug has been known to occur
Just found out 9/24/17

#### Server revision & Game ID
Server revision: master - 2017-09-24
f1abb40c8aae2202a15c9894149e9029ffcd319f 
Game ID: bQC-dKIW

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x ] Issue could be reproduced at least once
- [x ] Issue could be reproduced by different players
- [x ] Issue could be reproduced in multiple rounds
- [x ] Issue happened in a recent (less than 7 days ago) round
- [x ] [Couldn't find an existing issue about this](https://github.com/Yonaguni/EuropaStation/issues)

**Comment by Zuhayr** [comment]
Could not reproduce this, feeding 20 gold bars into the circuit imprinter produced 40k gold in the lathe menu, which translates accurately to 2000 gold per bar.
