### ISSUE TITLE
Yonaguni Main Dome - Southern Hallway APC weirdness

### ISSUE THREAD

**Issue by BlackRoseVertigo** [Yonaguni/EuropaStation#647]
#### Description of issue
Main Dome - Southern Hallway APC located in a hallway between cargo and engineering is not connected to the main grid, powers the whole southern hallway between cargo and medbay but does not draw any power from APC battery when engine is running, nor recharges it (because its off the grid). Loads just say 0. Yet when you turn the main breaker off it depowers the whole hallway.

#### Difference between expected and actual behavior
I guess it should drain its battery as it is powering the whole hallway?..
Although it appears to be draining the cell when engine havent been set up in the previous rounds...

#### Specific information for locating

Main Dome - Southern Hallway APC, between cargo and engineering, or just north outside the tool storage.

#### Length of time in which bug has been known to occur

Couple of days.

#### Server revision & Game ID

Server revision: master - 2017-09-25
c6fe2bb9a2bdd6dd9ff10ad6b6ec29da869cc02d 
Game ID: bQE-burL

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/Yonaguni/EuropaStation/issues)

**Comment by Zuhayr** [comment]
Fixed.
