### ISSUE TITLE
Autolathe magasine production wierdness

### ISSUE THREAD

**Issue by Adronio** [Yonaguni/EuropaStation#652]
#### Description of issue
Any magasine/ammo belt/speedloader produced is chambered for .357, including assault rifle magasines.

#### Difference between expected and actual behavior
The magasines should actually be usable by the guns in the game, but since there currently are no .357's every mag produced by autolathes are useless.

#### Steps to reproduce 
Just create a magasine with the autolathe.

#### Specific information for locating

Autolathe, magasine

#### Length of time in which bug has been known to occur

For however long we could produce magasines with autolathes. 2 days or something like that.

#### Server revision & Game ID

Not needed.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Yonaguni/EuropaStation/issues)

**Comment by Zuhayr** [comment]
Fixed.
