### ISSUE TITLE
Ammo production takes too long

### ISSUE THREAD

**Issue by Adronio** [Yonaguni/EuropaStation#653]
#### Description of issue
Producing one (1) bullet/shell of any type in the ammo press takes as much time as creating one (1) item of any size on the autolathe. I think it is about 5-8 seconds long. This is too long, as now you have to stay at the ammo press for 5 minutes just to get a half decent backstop of shotgun shells, not to say assault rifle bullets which would take ages to get even one mag filled.

#### Difference between expected and actual behavior
Instead of creating 1 bullet/shell it should create something like for example 5 bullets/shells every time, or maybe something variable like 7 pistol bullet, 5 rifle bullets or 3 shotgun shells each time. Adjust material consumption to fit.

#### Steps to reproduce 
Use the ammo press.

#### Length of time in which bug has been known to occur

Not a bug.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Yonaguni/EuropaStation/issues)

**Comment by Zuhayr** [comment]
Fixed.
