### ISSUE TITLE
Cannot Select Electrician Overalls In Loadout

### ISSUE THREAD

**Issue by redstryker** [Yonaguni/EuropaStation#669]
#### Description of issue
Exactly as the title says.

#### Difference between expected and actual behavior
I expected to be able to click on the overalls and have them added to my loadout list.  The item was not selected.

#### Steps to reproduce 
Character Setup>Loadout>Overalls
Click 'overalls, electrician'

#### Specific information for locating
N/A

#### Length of time in which bug has been known to occur
No idea.  Just saw it now.

#### Server revision & Game ID
Server revision: master - 2017-10-02
44433a77657957eeff245351ad6d8334356995c8 
Game ID: bQK-a2be

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Yonaguni/EuropaStation/issues)

**Comment by Zuhayr** [comment]
Fixed.
