### ISSUE TITLE
Makara: No gutters.

### ISSUE THREAD

**Issue by BlackRoseVertigo** [Yonaguni/EuropaStation#676]
#### Description of issue
Couldnt find a single gutter on Makara for water to go to. You get out of an airlock and it just spills everywhere.

#### Difference between expected and actual behavior
On a submarine i would expect something to get rid of the water.

#### Steps to reproduce 
Just add water.

#### Server revision & Game ID

Server revision: makara - 2017-10-17
7ed0d83ab5ee4525de991018dfa400e759f500aa 
Game ID: bQ1-bOEr

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/Yonaguni/EuropaStation/issues)

**Comment by Zuhayr** [comment]
This is fixed.
