### ISSUE TITLE
Robots telekineticly remove fuel rods from injectors

### ISSUE THREAD

**Issue by BlackRoseVertigo** [Yonaguni/EuropaStation#677]
#### Description of issue
Simply clicking a inactive injector in sight as a robot would teleport the rod from it to your turf.

#### Difference between expected and actual behavior
I guess one would have to use gripper thing to pull the rod out while standing next to it.

#### Steps to reproduce 
Get LoS on the inactive injector with a rod in. Click on the injector. 

#### Specific information for locating

First seen by me on Makara.

#### Server revision & Game ID

Server revision: makara - 2017-10-17
7ed0d83ab5ee4525de991018dfa400e759f500aa 
Game ID: bQ1-bOEr

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Yonaguni/EuropaStation/issues)

**Comment by Zuhayr** [comment]
This was fixed at some point.
