### ISSUE TITLE
Travis is failing master

### ISSUE THREAD

**Issue by HeyBanditoz** [Yonaguni/EuropaStation#721]
#### Description of issue
Travis has given up.

#### Difference between expected and actual behavior
This shouldn't be happening.

#### Steps to reproduce 
Look at the latest commit.

#### Specific information for locating
Travis configs? Wouldn't know.

#### Length of time in which bug has been known to occur
Since 381932c4c98c312b65326915d92d16232826fbca it looks like.

#### Server revision & Game ID
N/A

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Yonaguni/EuropaStation/issues)

**Comment by Zuhayr** [comment]
It's known, some kind of internal issue with Travis, not a repo bug. I'll look into it at some point.
