### ISSUE TITLE
Sprite visibility issues

### ISSUE THREAD

**Issue by 5crownik007** [Yonaguni/EuropaStation#728]
Several sprites i've encountered have been invisible when they shouldn't
examples include:

- Insulated gloves(see screenshot)

- Emergency shutters under construction

- Welding helmet pushed up inhand sprite(see screenshot)

- Railings(?)

https://i.gyazo.com/1b73aef3e0b35000d5ad5496fd20470a.png (insgloves(does not appear on mob)

https://i.gyazo.com/9d35e7fb28594e45371557e8372a7738.png (welding helmet(appears on mob))

There could be more of these I dunno but it's pretty annoying to walk out the airlock as a bald woman

**Comment by 5crownik007** [comment]
I think I found the problem as to why welding helmets become invisible but I have to do a bit of testing first to see if i can fix it

**Comment by 5crownik007** [comment]
Railings have no icon state defined in their variables

**Comment by Zuhayr** [comment]
Deleted reference to hardsuit helmets as they have their own issue. Will have a commit up for these shortly.
