### ISSUE TITLE
/material/glass of wine

### ISSUE THREAD

**Issue by Nyvrem** [Yonaguni/EuropaStation#800]
#### Description of issue
Glasses of wine from the Booze-O-Mat show up as /material/glass of wine

#### Difference between expected and actual behavior
I expected a glass of wine, not a /material/glass of wine

#### Steps to reproduce 
Get a glass of wine from the Booze-O-Mat

#### Specific information for locating

/material/glass of wine

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/Yonaguni/EuropaStation/issues)

**Comment by Nyvrem** [comment]
You also seem to get the:
You can't see any useful way to use /material/glass of lime juice on Test Dummy.
Message after one sip.

**Comment by Zuhayr** [comment]
Dammit I thought I fixed this.
