### ISSUE TITLE
The Drink Dispensers start empty

### ISSUE THREAD

**Issue by Nyvrem** [Yonaguni/EuropaStation#801]
#### Description of issue
The Booze Dispenser and Soft Drink Dispenser show up with "No cartridges installed!"

#### Difference between expected and actual behavior
I expected them to start with drinks.

#### Steps to reproduce 
Use the Drink Dispensers

#### Specific information for locating

No cartridges installed!

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/Yonaguni/EuropaStation/issues)

**Comment by Zuhayr** [comment]
I swear I fixed this too!
