### ISSUE TITLE
Map airlocks are currently set up for cycling to vacuum.

### ISSUE THREAD

**Issue by Zuhayr** [Yonaguni/EuropaStation#81]

**Comment by PJB3005** [comment]
Yeah fixing this will require changes to the cycling airlock system.

**Comment by Zuhayr** [comment]
GN worked out and I believe committed the required code changes, but the machinery required is quite different.

**Comment by Zuhayr** [comment]
@GinjaNinja32

**Comment by GinjaNinja32** [comment]
yep, will take a look when I setup Git on my new install

**Comment by GinjaNinja32** [comment]
god damnit i hate airlock code

will get to this soonish, might end up doing some sort of airlock rewrite, though

**Comment by PJB3005** [comment]
@GinjaNinja32 Yep airlock/door code is non OOP trash.

source: trying to make a door that only opens for cult.

**Comment by Loganbacca** [comment]
I've rewritten airlocks from scratch so they function properly on Europa now. All that needs to be done is for me to write some documentation so people know how to map them in.

**Comment by WrongEnd** [comment]
No longer using Box. New map will have airlocks set up for proper cycling at the start.

**Comment by Loganbacca** [comment]
@WrongEnd remind me to give you a run down on how to setup the new airlocks the next time you see me on irc.
